# Generated by Django 4.2.3 on 2023-07-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('money_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SharePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('one_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='spares', through='party.SharePart', to='party.member')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='party.party')),
            ],
        ),
        migrations.AddField(
            model_name='sharepart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.spareitem'),
        ),
        migrations.AddField(
            model_name='sharepart',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='party.party'),
        ),
        migrations.AddConstraint(
            model_name='sharepart',
            constraint=models.UniqueConstraint(fields=('member', 'item'), name='Must be unique'),
        ),
    ]
